### ISSUE TITLE
Pixelclock limit on Nvidia?

### ISSUE THREAD

**Issue by shad00m** [PMheart/CoreDisplayFixup#1]
Is this supposed to unlock the pixelclock limit on Nvidia cards to go above 330Mhz?
I've got a QNIX monitor but since High Sierra the other pixel clock unlocker doesn't work anymore.

**Comment by PMheart** [comment]
Hi, sorry for the late reply!

Actually, I have no idea if the limitation is in place or not. The patches are just taken from [here](https://github.com/Floris497/mac-pixel-clock-patch-v2) like I mentioned in README. Could you please try removing CoreDisplayFixup and test with the script from @floris497's repository?

**Comment by PMheart** [comment]
Any news here?

**Comment by Floris497** [comment]
Do you know if patch with your kext is working in 10.13? I have the patch ready but it's breaking stuff.. :/

**Comment by PMheart** [comment]
Unfortunately I don't. Actually my CoreDisplayFixup (CDF in context if mentioned) was initially written for a friend of mine, and I myself don't even have related device to test...
One thing is that he hasn't revealed anything not good so far, so I assume that CDF is still working, and surely I once heard that your manual script broke something (Copy/Paste stuffs if I remembered correctly) yet CDF didn't, I also have no idea though.

**Comment by Floris497** [comment]
Hey, I've made a whole new patch.. (now patched at 2 places actually) I guess the old patch is still working for Hackintosh but for genuine Mac it caused a black screen.. so I made a new one.. I will publish it soon after some testing.. if you have any questions about it.. please feel free to ask me somewhere or send an email.

**Comment by PMheart** [comment]
Ah, ok, I see. And now I have updated my CoreDisplayFixup to sync with your latest changes. :)

**Comment by Floris497** [comment]
Does it work well for hackintosh? I must say.. i have no idea how well the new patch will be working after updates.. we will see

**Comment by PMheart** [comment]
Well... I have no idea either, actually CDF is just a kext version of your script! Time will tell...

**Comment by Floris497** [comment]
Did you test it? :D

**Comment by PMheart** [comment]
Unfortunately not. I don't even have a appropriate device to test, like I said before CDF was initially written for a friend of mine, and he is the only tester that I'm acquainted...
