### ISSUE TITLE
qe/ci HD530 Quad HD HDMI

### ISSUE THREAD

**Issue by clickerpw** [PMheart/CoreDisplayFixup#10]
qe/ci not working  after cold start HD530 on 2K resolution

add: 
first(cold) start Windows 7 -> reboot in Mac OS-> Works!!!
first start Mac OS -> Artifacts -> reboot in Mac OS -> Works!!!
first start Mac OS -> Artifacts -> change resolution in System Pref to 1920x1080 -> change resolution in System Pref to 2560x1440 -> Works!!!

**Comment by PMheart** [comment]
Hi,

Unfortunately I don't know what is exactly wrong (CoreDisplayFixup is not written for me but for a friend of mine), anyway, I haven't heard any news about this, sorry...

**Comment by PMheart** [comment]
Have not heard any news for a while. Issue closed. Feel free to reopen if there is any further report.
