### ISSUE TITLE
Failed in 10.14 DB1

### ISSUE THREAD

**Issue by PtNan** [PMheart/CoreDisplayFixup#11]
I attempted to update to 10.14, found it that this kext cannot work
(clover ver 4515)

**Comment by buhlaze** [comment]
I tried floris's code and no luck also

**Comment by PMheart** [comment]
Hi,

Firstly, you can try booting with `-lilubeta` and `-cdfbeta` (Or maybe just use `-lilubetaall` instead). Yet @buhlaze said that Floris's manual patch did not work either... In this case it may indicate that certain frameworks have been changed, yet I haven't checked it and actually I'm not able to. CoreDisplayFixup was initially written for a friend of mine and I myself do not have such devices to test.

Regards,
PMheart

**Comment by buhlaze** [comment]
thank you so much for replying.

**Comment by Floris497** [comment]
As of now, I think my patch and the fixup kext do not share the same patch? (as old patch seemed to be working still in the method applied here but not in my script.. a slightly different part of code is patched with same results) will look for a new way :)

**Comment by al3xtjames** [comment]
Could you please try v1.3.7? It appears to work here (HD 4000/2560x1080 & HD 630/3840x2160), but further testing would be appreciated.

**Comment by buhlaze** [comment]
will be more than happy to

**Comment by PtNan** [comment]
ver1.3.7,It works perfectly.

**Comment by Floris497** [comment]
So is there a new patch? Guess I'm missing out on stuff while sleeping

**Comment by al3xtjames** [comment]
It's a slightly modified version of the existing CheckTimingWithRange patch (find/replace pattern changed a little):

https://github.com/PMheart/CoreDisplayFixup/blob/c9c37a1040584e38cd3ccc53b1dac15df988ba11/CoreDisplayFixup/IntelPatcher.cpp#L49-L60
