### ISSUE TITLE
Doesn't seem to work on 10.13.5

### ISSUE THREAD

**Issue by maddie** [PMheart/CoreDisplayFixup#12]
Hi,

The CoreDisplayFixup kext doesn't seem to work with `macOS 10.13.5 (17F77)`. Manually patching using Floris497's script with `patch v4` parameters does patch the CoreDisplay.kext successfully and got 4K output working again, but I'd prefer using Lilu plugins to achieve this result rather than changing system files..

Thanks.

**Comment by al3xtjames** [comment]
Hey,

What GPU are you using? I can't seem to reproduce this here (Intel HD Graphics 630, 3840x2160 display, also on 10.13.5). Also, have you tried rebuilding the DYLD shared cache?

**Comment by maddie** [comment]
Hi there,

It's an HD4600 on an i7-4790K, I haven't tried to rebuild the DYLD shared cache, perhaps that's the problem. I'll try and report back soon.

Thanks.

**Comment by maddie** [comment]
Hmm.. It seems to work fine after rebuilding the DYLD cache. Closing now.

Thanks!
