### ISSUE TITLE
Better explanation on how to install/run

### ISSUE THREAD

**Issue by marnovo** [PMheart/CoreDisplayFixup#3]
The [readme](https://github.com/PMheart/CoreDisplayFixup/blob/master/Instructions.md) and [instructions](https://github.com/PMheart/CoreDisplayFixup/blob/master/Instructions.md) provided assume a lot of knowledge of other tools and processes (that honestly aren't even properly covered in these tools repos).

It would be recommendable to have a clearer explanation, more like a get started or tutorial, even if doesn't cover every single aspect of it, in a similar way that [mac-pixel-clock-patch-V2](https://github.com/Floris497/mac-pixel-clock-patch-V2#how-to-use) does. Thanks!

**Comment by PMheart** [comment]
Hi!
First of all, thanks for your advice.
You surely need some basic skills before using CoreDisplayFixup, and I think here I have nothing to do with that. Just simply searching Google for the related topics instead.
