### ISSUE TITLE
compilation and usage

### ISSUE THREAD

**Issue by zohaad** [PMheart/CoreDisplayFixup#4]
Do I compile with the debug version of Lilu.kext and install the kext in the same directory as the Lilu.kext release version? Or can I use the debug version for both, what is recommended?

**Comment by PMheart** [comment]
Hi,

For normal use, just Lilu + CoreDisplayFixup (both RELEASE).
For debugging purposes, simply use DEBUG binaries instead.

**Comment by zohaad** [comment]
Thanks for the clarification, apparently I still can't get it compiled correctly for High Sierra, I get kernel panic:

as.vit9696.Lilu(1.2.2)[E650D28F-9633-3AA0-A938-35E22D295566]@0xffffff7f80b88000->0xffffff7f80bf1fff

**Comment by zohaad** [comment]
Also, why don't you include a pre-built kext?

**Comment by canyondust** [comment]
I also get kernel panic on boot (built with Lilu 1.2.1 for use with OSX 10.12.6)

**Comment by PMheart** [comment]
@zohaad 
As for compilation method, I have written something in README.
> Note: Debug version of Lilu.kext should be put in the same folder as CoreDisplayFixup! And they should also be used together!

I did release something in the release page, please check it out [here](https://github.com/PMheart/CoreDisplayFixup/releases).

@canyondust 
I don't think I'm the correct one to be asked for this. You may consider opening an issue directly to [Lilu](https://github.com/vit9696/Lilu/issues).

**Comment by canyondust** [comment]
Sorry, I should clarify: Lilu is working fine, I get a kernel panic when booting with CDF (which I compiled from current commit (1.3.3) with Lilu 1.2.1 debug) :)

**Comment by PMheart** [comment]
@canyondust Sorry for the misunderstanding, could you please post more details?

**Comment by zohaad** [comment]
I tried it with both pre built release kexts, same error:

It pauses a bit at `VM Swap Subsystem is ON` and then spits the following out really quickly before showing which kexts have been loading and showing the kernel panic error message.
```
panic(cpu 0 caller 0xffffff0000388e21): Kernel trap at 0xffffff000049b040, type=page fault, registers:
CR0: 0x0000....

Backtrace (CPU 0), Frame : Return Address
....
    Kernel Extensions in backtrace:
        as.vit9696.Lilu(1.2.2)[E650D28F-9633-3AA0-A938-35E22D295566]@0xffffff7f80b88000->0xffffff7f80bf1fff
```

This data may be incorrect as it's hard to read from a video (used slow-motion mode to capture) with tiny letters at 3200x1800 at a quick speed. If you have ideas on how to capture this data (Clover's -v mode), please let me know.

**Comment by zohaad** [comment]
Forgot to mention my hardware: Lenovo Yoga 3 Pro with 3200x1800 screen and Core M-5Y70 processor with HD 5300 graphics

**Comment by canyondust** [comment]
6700K+GTX1080 here, here's a photo of the screen right before it auto-restarts.
![file 2018-01-07 3 45 03 pm](https://user-images.githubusercontent.com/35182577/34653933-0b997582-f3c2-11e7-88da-74941e2af6ab.jpeg)

**Comment by PMheart** [comment]
@zohaad @canyondust 
Could you please try DEBUG Lilu & CoreDisplayFixup binaries (You can download them [here](https://github.com/PMheart/CoreDisplayFixup/releases/download/1.3.3/1.3.3.DEBUG.zip) and [here](https://github.com/vit9696/Lilu/releases/download/1.2.1/1.2.1.DEBUG.zip))
And please boot with `-v -liludbgall keepsyms=1 debug=0x100` and then upload the panic picture here. (Maybe even a video record for the whole progress I guess, which is better)

**Comment by zohaad** [comment]
The display moves really fast, I tried recording with slow-mo mode:


https://drive.google.com/file/d/1SDcR_ybsreitpSV7uk3yUWd1u5IvDeS7/view?usp=sharing
https://drive.google.com/file/d/1ySqsf6NK5uvwH_4CYyWTK7yQBcGGXxE4/view?usp=sharing

**Comment by zohaad** [comment]
Somehow the problem has been resolved by updating to the latest version of macOS: 10.13.2

kextstat now shows CoreDisplayFixup loaded right after Lilu

**Comment by PMheart** [comment]
@zohaad Glad to hear that!
@canyondust Any news?

**Comment by zohaad** [comment]
There is another issue with CoreDisplayFixup I believe, see picture attached.
![img_0122](https://user-images.githubusercontent.com/10496606/35248689-5e406606-ffcf-11e7-84a4-3a9c998d168c.jpg)

Notable lines:
`VM Swap Subsystem is ON`
Then the screen flashes. I think windowserver crashes here, I may be wrong though.
`Lilu:    file @ failed to find /System/Library/Frameworks/CoreGraphics.framework/Versions/A/Resources/WindowServer`

Also:

`Unsupported CPU for reporter`

**Comment by PMheart** [comment]
It is expected because `/System/Library/Frameworks/CoreGraphics.framework/Versions/A/Resources/WindowServer` is for 10.10.x, and for your OS (maybe 10.13.x I guess?) it's simply missing.

Unfortunately I have no idea for now, have you tested my latest 1.3.4, by the way?

**Comment by PMheart** [comment]
Any news here?

**Comment by yuhengliang** [comment]
can’t work on I78550   UHD620 with 4K display.  type: HP ENVY X360 15bp-107tx
![qq 20180330175034](https://user-images.githubusercontent.com/388165/38147690-f4c2994c-3485-11e8-8311-32f95e8d799c.jpg)

**Comment by PMheart** [comment]
1.3.6 is out, which added 10.13.4+ compatibility, give it a try.

**Comment by PMheart** [comment]
Have not heard any news for a while. Issue closed. Feel free to reopen if there is any further report.
