### ISSUE TITLE
New Version can’t work on HD530 with 4K display.

### ISSUE THREAD

**Issue by gujiangjiang** [PMheart/CoreDisplayFixup#5]
Error on IGPU

I revert to the past version and works well.

**Comment by gujiangjiang** [comment]
Test again with audio update_dyld balabala but still not work.

I supposed new patch for 10.13.2 are wrong or have something not work.

**Comment by Floris497** [comment]
What does not work? Do you have more detailed error info?

**Comment by PMheart** [comment]
Hello,

Could you please try the way I mentioned [here](https://github.com/PMheart/CoreDisplayFixup/issues/4#issuecomment-355960708) and upload all relevant information? Thanks in advance.

[UPDATE]
Looks like @Floris497's new patch is problematic (I can't tell why for the time being though), I've reverted back to the old one and bumped CoreDisplayFixup to 1.3.4. Please try: https://github.com/PMheart/CoreDisplayFixup/releases/tag/1.3.4

Regards,
PMheart

**Comment by gujiangjiang** [comment]
OK .

Tried 1.3.4 and works well now.

Thanks for your hard work!

Good wishes.
