### ISSUE TITLE
Broken in 10.3.4 Beta 1

### ISSUE THREAD

**Issue by TylerD89** [PMheart/CoreDisplayFixup#6]
Hey just a heads up, the latest version seems to be broken in 10.13.4. The computer still boots, but the resolution is back to 1920x1080. If you need me to test anything just reply back. Thanks

**Comment by PMheart** [comment]
Hi!

Unfortunately I have no idea. I don't use Beta. I may have a look after the final release of 10.13.4.

**Comment by TylerD89** [comment]
Oh okay. Thanks anyway, it’s probably just a compatibility issue... I’ll take a look at the logs later

**Comment by TylerD89** [comment]
Stumped here... However, Floris's manual script is working for now! Marking as closed...

**Comment by buhlaze** [comment]
This will not work and stuck at black screen on 10.13.4 on dell xps 15 9560 (4K screen). Was working fine in 10.13.3 and below.

**Comment by PMheart** [comment]
Hi!
Do you mean 10.13.4 Beta? If so, it's a known issue. Please use floris497's script for now.
Sorry, I'm extremely busy these days and 10.13.4 is still a pre-release... Anyway, I'll take a look after the final release.

Thank you,
PMheart

**Comment by TylerD89** [comment]
@buhlaze Link to GitHub Page [here](https://github.com/Floris497/mac-pixel-clock-patch-V2)... Since you are in a beta, the script will complain that there isn't a valid MD5 hash... You have to force the patch by using the "patch v4" flag in the terminal. Read the Readme, it will go over it better

**Comment by buhlaze** [comment]
Thank you TylerD89, that fixed me up well and 4k graphics are working great on 10.13.4 Beta.

**Comment by TylerD89** [comment]
No problemo 👍
