### ISSUE TITLE
Cannot work in 10.13.4

### ISSUE THREAD

**Issue by PtNan** [PMheart/CoreDisplayFixup#8]
I was updating to 10.13.4 and got stuck,
`IOConsoleUsers: gIOScreenLockState 3,hs 0, bs 0, now 0, sm0x0`

**Comment by al3xtjames** [comment]
Could you try the attached version (this is with #7):

[1.3.5 (RELEASE).zip](https://github.com/PMheart/CoreDisplayFixup/files/1862649/1.3.5.RELEASE.zip)

**Comment by PtNan** [comment]
That's good.Thanks
