### ISSUE TITLE
can’t work on I7 8550U   UHD620 with 4K display. 

### ISSUE THREAD

**Issue by yuhengliang** [PMheart/CoreDisplayFixup#9]
can’t work on I7 8550U   UHD620 with 4K display.  type: HP laptop ENVY X360 15bp-107TX 

thinks! 

![qq 20180330175034](https://user-images.githubusercontent.com/388165/38147690-f4c2994c-3485-11e8-8311-32f95e8d799c.jpg)

**Comment by PMheart** [comment]
Hi,

[1.3.6](https://github.com/PMheart/CoreDisplayFixup/releases/tag/1.3.6) should be the solution, give it a try.

Regards,
PMheart

**Comment by PMheart** [comment]
Have not heard any news for a while. Issue closed. Feel free to reopen if there is any further report.
